### ISSUE TITLE
unable to install extension

### ISSUE THREAD

**Issue by Badrouu17** [oessaid/react-theme-faithful#1]
![vcds](https://user-images.githubusercontent.com/55046912/78218191-46908380-74b5-11ea-8f56-e3436d8c80f5.jpg)

**Comment by oessaid** [comment]
Hi @Badrouu17, thanks for taking the time to report this. In the extension's manifest,  it is set to support VS Code from 1.41.0 onwards (current VS Code version is 1.43) for the simple reason that it is the version I used to develop this.

As I haven't tested with previous versions of VS Code, I'm hesitant to change that minimal version tag.

Any chance you could update your VS Code app instead? Is anything preventing you from doing so?

**Comment by Badrouu17** [comment]
Thanks for responding, just updating vscode fix it for me 👍

**Comment by oessaid** [comment]
Glad it worked out for you, closing the issue.
